[package]
name = "fetch-cargo-index"
version = "0.1.0"
edition = "2024"

[dependencies]
crates-index = { version = "3.11.0", features = ["git-https", "git-performance"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[profile.release]
lto = "thin"
panic = "abort"
